version: '3.9'
services:
  fast-cloud-gateway:
    image: fast:1.0
    container_name: fast-plus-gateway
    ports:
      - 8080:8080
    env_file:
      - app.env
    volumes:
      - /work/www/fast-plus/fast-cloud-gateway.jar:/app/app.jar
  fast-cloud-system:
    image: fast:1.0
    container_name: fast-cloud-system
    env_file:
      - app.env
    volumes:
      - /work/www/fast-plus/fast-cloud-system.jar:/app/app.jar